#!/usr/bin/env fish

set pass 0

set url (vantage pg url test_url_unknown_name)

if test $status -eq 0
    echo "Expecting failure status code, got $status"
    set pass 1
end

if test -n "$url"
    echo "Expecting empty response, got $url"
    set pass 1
end

exit $pass
