#!/bin/bash
set -e

URL=$(vg __env DATABASE_URL)

docker run \
    --rm \
    postgres pg_dump \
        --format=custom \
        --no-acl \
        --no-owner \
        --schema=public \
        --dbname="$URL"
