#!/bin/bash
set -e

function random_string {
    head /dev/urandom | LC_ALL=C tr -dc a-z0-9 | head -c 12
}

USERNAME=$(random_string)
PASSWORD=$(random_string)
DB_NAME=$(random_string)
CONTAINER_NAME="vg-pg-$(random_string)"

NETWORK=""
if [ -n "$VG_DOCKER_NETWORK" ]; then
    NETWORK="--network=$VG_DOCKER_NETWORK"
fi

CONTAINER=$(docker run \
    --env POSTGRES_USER=$USERNAME \
    --env POSTGRES_PASSWORD=$PASSWORD \
    --env POSTGRES_DB=$DB_NAME \
    $NETWORK \
    --label vantage.pg=1 \
    --publish 5432 \
    --detach \
    --name "$CONTAINER_NAME" \
    postgres)

if [ -n "$VG_DOCKER_NETWORK" ]; then
    HOST="$CONTAINER_NAME"
else
    HOST=$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' $CONTAINER)
fi


DB="postgres://$USERNAME:$PASSWORD@$HOST:5432/$DB_NAME"

vg __env DATABASE_URL "$DB"

echo "$DB"
