#!/bin/bash
set -e

function help {
    cat << EOF >&2
usage: vantage pg dump|fixtures|migrate|new|ping|restore|rm|shell|web

This plugin assumes that a database URI will be available at the ENV variable
DATABASE_URL. It should look something like this:

    DB_TYPE://USERNAME:PASSWORD@HOST:PORT/DB_NAME

Commands:
    dump - Output a simple pg_dump of the DB to stdout
    fixtures FIXTURE_NUMBER [FIXTURE_NUMBER...] - Load fixture data
    migrate MIGRATION_NUMBER [MIGRATION_NUMBER...] - Run schema migrations
    new - Create a new postgreSQL DB and save the URI to the default env file
    ping - Try to connect to the DB
    restore DUMP_FILE - Restore the DB from the DUMP_FILE into a new DB
    rm [-a] - Remove the DB container, or all containers if the -a flag is set
    shell - Open a psql shell pointed at the DB
    web - Start up a pgweb instance pointed at the DB

See the GitHub repo for more details (https://github.com/vantage-org/pg)

EOF
}

if [ -n "$VG_SHOW_HELP" ]; then
    help
    exit
fi

echo "vantage: pg: No command given"
exit 1
