#!/bin/bash

url=$(vg __env DATABASE_URL)

attempts=10
while [ $attempts -ge 0 ]
do
    attempts=$(( $attempts - 1 ))
    echo -n "Trying to connect..."
    docker run --rm postgres psql --dbname="$url" &> /dev/null
    if [ $? -eq 0 ]; then
        echo " Success!"
        exit 0
    else
        echo " Failed"
    fi
    sleep 1
done

exit 1
