#!/bin/bash

URL=$(vg __env DATABASE_URL)

ATTEMPTS=10
while [ $ATTEMPTS -ge 0 ]; do
    ATTEMPTS=$(( $ATTEMPTS - 1 ))
    echo -n "Trying to connect..."
    docker run --rm postgres psql --dbname="$URL" &> /dev/null
    if [ $? -eq 0 ]; then
        echo " Success!"
        exit 0
    else
        echo " Failed"
    fi
    sleep 1
done

exit 1
