#!/bin/bash
set -e

URL=$(vg pg new)
vg -v "DATABASE_URL=$URL" pg ping > /dev/null

docker run \
    --volume "$1:/data.dump" \
    --rm \
    postgres pg_restore \
        --no-acl \
        --no-owner \
        --schema=public \
        --dbname="$URL" \
        /data.dump > /dev/null

echo $URL
