#!/bin/bash
set -e

URL=$(vg __env DATABASE_URL)

NETWORK=""
if [ -n "$VG_DOCKER_NETWORK" ]; then
    NETWORK="--network=$VG_DOCKER_NETWORK"
fi

docker run \
    --interactive \
    --tty \
    --rm \
    $NETWORK \
    postgres psql --dbname "$URL"
