#!/bin/bash
set -e

url=$(vg __env DATABASE_URL)

docker run \
    --publish 8081:8081 \
    --rm \
    --env "DATABASE_URL=$url" \
    sosedoff/pgweb /usr/bin/pgweb --bind=0.0.0.0 --listen=8081 --skip-open --ssl=disable
