#!/usr/bin/env fish

set pass 0

# Remove by name
set count_before (vantage pg count)
vantage pg new --name test_rm
vantage pg rm --name test_rm
set count_after (vantage pg count)

if test $count_before -ne $count_after
    echo "There were $count_before DBs before and $count_after after"
    echo "A DB should have been created and then removed by name"
    set pass 1
end

if vantage pg ping --name test_rm
    echo "I can ping the removed by name DB"
    set pass 1
end

# Remove by url
set count_before (vantage pg count)
set url (vantage pg new)
vantage pg rm --url "$url"
set count_after (vantage pg count)

if test $count_before -ne $count_after
    echo "There were $count_before DBs before and $count_after after"
    echo "A DB should have been created and then removed by url"
    set pass 1
end

if vantage pg ping --url "$url"
    echo "I can ping the removed by url DB"
    set pass 1
end

# Remove by env
set count_before (vantage pg count)
set url (vantage pg new)
vantage env DATABASE_URL "$url"
vantage pg rm
set count_after (vantage pg count)

if test $count_before -ne $count_after
    echo "There were $count_before DBs before and $count_after after"
    echo "A DB should have been created and then removed by env"
    set pass 1
end

if vantage pg ping --url "$url"
    echo "I can ping the removed by env DB"
    set pass 1
end

# Remove all
vantage pg new
vantage pg new
vantage pg new
vantage pg rm --all
set count_after (vantage pg count)

if not test $count_after -eq 0
    echo "There were $count_after DBs there should have been 0"
    set pass 1
end

# Can't rm bad URL
if vantage pg rm --url "not://a:real@url:123/see"
    echo "Could rm a fake URL"
    set pass 1
end

# Can't rm bad name
if vantage pg rm --name not_a_name
    echo "Could rm a fake name"
    set pass 1
end

# Can't rm twice
vantage pg new --name test_rm_twice
vantage pg rm --name test_rm_twice
if vantage pg rm --name test_rm_twice
    echo "Could rm twice"
    set pass 1
end

exit $pass
