#!/usr/bin/env fish

set pass 0

set url (vantage pg new --name test_ping)

# Ping by url
if not vantage pg ping --url "$url"
    echo "Could not ping by URL"
    set pass 1
end

# Ping by name
if not vantage pg ping --name test_ping
    echo "Could not ping by name"
    set pass 1
end

# Ping by ENV
vantage env DATABASE_URL "$url"
if not vantage pg ping
    echo "Could not ping using ENV"
    set pass 1
end

# Can't ping bad URL
if vantage pg ping --url "not://a:real@url:123/see"
    echo "Could ping a fake URL"
    set pass 1
end

# Can't ping bad name
if vantage pg ping --name not_a_name
    echo "Could ping a fake name"
    set pass 1
end

# Can't ping bad credentials (remove the first char of the username)
set bad_url (echo "$url" | sed "s/postgresql:\/\/./postgresql:\/\//g")
if vantage pg ping --url "$bad_url"
    echo "Could ping with bad credentials"
    set pass 1
end

vantage pg rm --name test_ping

exit $pass
