#! /bin/bash
set -eu

FIXTURES_DIR="${VG_PG_FIXTURES_DIR:-$VG_APP_DIR/fixtures}"

URL=$(vantage __env DATABASE_URL)

NETWORK=""
if [ -n "$VG_DOCKER_NETWORK" ]; then
    NETWORK="--network=$VG_DOCKER_NETWORK"
fi

for i in "$@"; do
    for path in "$FIXTURES_DIR/$i-"*.sql; do
        name=$(basename "$path")
        docker run \
            --volume "$FIXTURES_DIR:/data" \
            --rm \
            "$NETWORK" \
            postgres psql --dbname "$URL" --file "/data/$name"
    done
done
