#! /bin/bash
set -eu

MIGRATIONS_DIR="${VG_PG_MIGRATIONS_DIR:-$VG_APP_DIR/migrations}"

URL=$(vantage __env DATABASE_URL)

NETWORK=""
if [ -n "$VG_DOCKER_NETWORK" ]; then
    NETWORK="--network=$VG_DOCKER_NETWORK"
fi

for i in "$@"; do
    for path in "$MIGRATIONS_DIR/$i-"*.sql; do
        name=$(basename "$path")
        docker run \
            --volume "$MIGRATIONS_DIR:/data" \
            --rm \
            "$NETWORK" \
            postgres psql --dbname "$URL" --file "/data/$name"
    done
done
