#!/bin/bash
set -e

URL=$(vantage __env DATABASE_URL)

NETWORK=""
if [ -n "$VG_DOCKER_NETWORK" ]; then
    NETWORK="--network=$VG_DOCKER_NETWORK"
fi

SSL="--ssl=${VG_PG_WEB_SSLMODE:-require}"

docker run \
    --publish 8081:8081 \
    --rm \
    --env "DATABASE_URL=$URL" \
    "$NETWORK" \
    sosedoff/pgweb /usr/bin/pgweb --bind=0.0.0.0 --listen=8081 --skip-open "$SSL"
