#!/bin/sh
# ---
# help-text: Restore a database dump into the current database
# image:
#   tag: "postgres:$VG_PG_VERSION"
#   network: $VG_DOCKER_NETWORK
#   rm: true
#   interactive: true
# defaults:
#   VG_PG_VERSION: latest
#   VG_DOCKER_NETWORK: host
# ---
pg_restore \
    --no-acl \
    --no-owner \
    --schema=public \
    --dbname="$DATABASE_URL"
