#!/usr/bin/env fish

set pass 0

# Create a new DB and count the running containers before and after
set count_before (vantage pg count)
set o (vantage pg new)
set count_after (vantage pg count)

vantage pg ping --url "$o"

if test $status -ne 0
    echo "Could not ping DB $o"
    set pass 1
end

if not test (math $count_before + 1) -eq $count_after
    echo "There were $count_before DBs before and $count_after after"
    set pass 1
end

vantage pg rm --url "$o"

# This time create using a name
set o (vantage pg new --name my_test_db)

vantage pg ping --name my_test_db

if test $status -ne 0
    echo "Could not ping DB my_test_db"
    set pass 1
end

set o (docker ps | grep postgres | grep my_test_db | wc -l)

if test "$o" != "1"
    echo "Expecting docker to have 1 my_test_db it had $o"
    set pass 1
end

vantage pg rm --name my_test_db

exit $pass
