#!/usr/bin/env fish

set pass 0

docker run --detach --name url_not_pg_name postgres

set url (vantage pg url url_not_pg_name)

set code $status

docker stop url_not_pg_name
docker rm url_not_pg_name

if test $code -eq 0
    echo "Expecting failure status code, got $status"
    set pass 1
end

if test -n "$url"
    echo "Expecting empty response, got $url"
    set pass 1
end

exit $pass
